/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'yukung' at '15/11/08 14:10' with Gradle 2.8
 *
 * @author yukung, @date 15/11/08 14:10
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
