/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'yukung' at '16/06/12 16:41' with Gradle 2.13
 *
 * @author yukung, @date 16/06/12 16:41
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
