/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yukung' at '15/11/08 17:07' with Gradle 2.8
 *
 * @author yukung, @date 15/11/08 17:07
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
